### ISSUE TITLE
ipban command not being able to find banned.json

### ISSUE THREAD

**Issue by nahilep** [RanvierMUD/bundle-example-debug#1]
https://github.com/RanvierMUD/bundle-example-debug/blob/master/commands/ipban.js#L30
the  `FIXME` above this line already states that this has to be fixed, since `bundlePath` is completely undefined here, this should indeed be an issue.

**Comment by shawncplus** [comment]
This touches a bit on the data layer change I want to make. For the moment it's probably enough to just have the file in the bundle itself instead of going up into the main data folder

**Comment by nahilep** [comment]
`ipban` is not working the way it is written. `bannedList.push(target.socket.address().address);` is the issue at the moment. `target.socket.address()` is `null` and has no property `address`. I haven't been able to find the ip of a socket. Any hints?
